'use strict';

/**
 * Blocks em dashes and en dashes from entering the codebase:
 * `npm run check:dashes`. Installed as a pre-commit hook by
 * `npm run hooks:install`, beside the secret check.
 *
 * Why this exists: an em dash is the clearest fingerprint of text generated by
 * an assistant rather than written by the team, and 517 of them had accumulated
 * across 102 files. They also cost real money at the boundaries - a `-` survives
 * a Windows-1252 console, a CSV opened in Excel and a jsPDF font that has no
 * glyph for U+2014, where an em dash turns into a replacement box.
 *
 * The rule is deliberately absolute. "Only in user-facing strings" or "only in
 * comments" needs a judgement call at every commit, and a guard that argues is
 * a guard that gets bypassed. ASCII `-` everywhere, no exceptions to remember.
 *
 * Scope: staged files under a pre-commit run, the whole tree otherwise. Applied
 * migrations are exempt - Prisma checksums them, so editing one after it has run
 * breaks `migrate deploy` on every machine that already applied it.
 */

const fs = require('node:fs');
const path = require('node:path');
const { execSync } = require('node:child_process');

const ROOT = path.resolve(__dirname, '..');

/**
 * Written as escapes, never as the glyph itself: this file would otherwise
 * fail its own check, and exempting it would give a real dash somewhere to
 * hide.
 */
const EM = '\u2014';
const EN = '\u2013';

const BANNED = [
  [EM, 'em dash', '-'],
  [EN, 'en dash', '-'],
];

const BANNED_RE = /[\u2013\u2014]/;

/** Binary and generated content: nothing to read, nothing a human wrote. */
const SKIP_EXT = new Set([
  '.png', '.jpg', '.jpeg', '.gif', '.ico', '.webp', '.svg',
  '.pdf', '.woff', '.woff2', '.ttf', '.eot', '.zip', '.lock',
]);

/**
 * Prisma records a checksum for every migration it has applied. Rewriting one
 * after the fact makes `migrate deploy` refuse to run against any database that
 * already has it, so these stay exactly as they were shipped.
 */
const SKIP_PATH = [
  /(^|\/)prisma\/migrations\//,
  /(^|\/)package-lock\.json$/,
  /(^|\/)node_modules\//,
  /(^|\/)dist\//,
  // The document that defines this rule has to print the characters it bans.
  /(^|\/)docs\/CONVENTIONS_TEXTE\.md$/,
];

const isSkipped = (rel) =>
  SKIP_EXT.has(path.extname(rel).toLowerCase()) || SKIP_PATH.some((re) => re.test(rel));

/**
 * Staged files when run as a hook, every tracked file otherwise.
 *
 * The full run deliberately includes untracked-but-not-ignored files: a brand
 * new file is exactly where a dash arrives, and `git ls-files` alone does not
 * see it until it is added. `--exclude-standard` keeps .gitignore honoured, so
 * .env and node_modules stay out.
 */
function targets() {
  const staged = process.argv.includes('--staged');
  const cmd = staged
    ? 'git diff --cached --name-only --diff-filter=ACM'
    : 'git ls-files --cached --others --exclude-standard';
  return execSync(cmd, { cwd: ROOT, encoding: 'utf8' })
    .split('\n')
    .map((f) => f.trim())
    .filter(Boolean)
    .filter((rel) => !isSkipped(rel));
}

const findings = [];

for (const rel of targets()) {
  const abs = path.join(ROOT, rel);
  let text;
  try {
    text = fs.readFileSync(abs, 'utf8');
  } catch {
    // Deleted between staging and now, or genuinely binary. Not our problem.
    continue;
  }
  if (!BANNED_RE.test(text)) continue;

  text.split('\n').forEach((line, i) => {
    for (const [char, name] of BANNED) {
      if (!line.includes(char)) continue;
      findings.push({
        file: rel,
        line: i + 1,
        name,
        // Show the offender in context, with the dash made visible.
        excerpt: line.trim().slice(0, 100).replaceAll(char, `>>${char}<<`),
      });
    }
  });
}

if (findings.length === 0) {
  console.log('  No em dashes or en dashes. Clean.');
  process.exit(0);
}

console.error(`\n  ${findings.length} banned dash(es) found:\n`);
for (const f of findings.slice(0, 40)) {
  console.error(`  ${f.file}:${f.line}  (${f.name})`);
  console.error(`    ${f.excerpt}\n`);
}
if (findings.length > 40) {
  console.error(`  ...and ${findings.length - 40} more.\n`);
}
console.error('  Replace every one with an ASCII hyphen "-".');
console.error(`  A spaced parenthetical " ${EM} " becomes " - ".\n`);
process.exit(1);
